// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: tpbzyemgrvfrngjhouqj

class SupabaseConfig {
  static const String supabaseUrl = 'https://tpbzyemgrvfrngjhouqj.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwYnp5ZW1ncnZmcm5namhvdXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExMDkxOTgsImV4cCI6MjA3NjY4NTE5OH0.IdRd6AZLmtTQCd5aGH7NXkcsbfbUxiRqeiBkyNoAw-I';
}
